"""create user_sessions table

Revision ID: 068d2ba2f0b8
Revises: 39c4deb7cc1f
Create Date: 2026-03-27 13:53:21.558969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068d2ba2f0b8'
down_revision: Union[str, Sequence[str], None] = '39c4deb7cc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('deviceInfo', sa.String(), nullable=False),
    sa.Column('isRevoked', sa.Boolean(), nullable=False),
    sa.Column('rememberMe', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_sessions', schema='auth')
    # ### end Alembic commands ###
